//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTypesEnum
    {
        public long ID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Synonyms { get; set; }
        public int OrderBy { get; set; }
        public bool IsDefault { get; set; }
        public bool Disabled { get; set; }
    }
}
