// <auto-generated />
using System;
using DLEFCore2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DLEFCore2.Migrations
{
    [DbContext(typeof(DLEFCoreContext))]
    [Migration("20240925073609_AddNumbersToUserModel")]
    partial class AddNumbersToUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DLEFCore2.Repository.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age1")
                        .HasColumnType("int");

                    b.Property<long>("Age2")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive2")
                        .HasColumnType("bit");

                    b.Property<string>("Name1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Ronnie");

                    b.Property<string>("Name11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .IsRequired()
                        .HasMaxLength(257)
                        .HasColumnType("nvarchar(257)");

                    b.Property<decimal>("value1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("value2")
                        .HasColumnType("float");

                    b.Property<float>("value3")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
